export const Labels = {
  inicio: 'Início',
  carrinho: 'Carrinho',
  checkout: 'Checkout',
  frutcom: 'Frutcom',
  pesquisar: 'Pesquisar',
  frutas: 'Frutas',
  vegetais: 'Vegetais',
  organic: 'Organic',
  maca: 'Maçã',
  banana: 'Banana',
  pera: 'Pera',
  abacaxi: 'Abacaxi',
  manga: 'Manga',
  minhaLista: 'Minha Lista',
  obtenhaAte: 'Obtenha até',
  dezOff: '10% off',
  umKg: '1kg',
  frutasFrescas: 'Frutas frescas para você',
  sejaBem: 'Seja Bem-Vindo(a)',
  facilidadePara: 'Facilidade para suas compras',
  usuarioEOu: 'Usuário e/ou senha inválidos',
  UsuarioNao: 'Usuário não cadastrado no sistema',
  lembrarMe: 'Lembrar-me',
  login: 'Login',
  senha: 'Senha',
  cpf: 'CPF',
  priceBanana: 9.79,
  priceMaca: 4.99,
  pricePera: 10.99,
  priceAbacaxi: 5.99,
  priceManga: 3.79,
  buttonCheckout: (t) => `R$${t} Checkout`,
  valorTotal: 'Valor Total',
  cliente: 'Cliente',
  compartilharPDF: 'Compartilhar PDF',
  preenchaOsCampos: 'Preencha os campos corretamente',
  nenhumItem: 'Nenhum item',
  voceNaoPossui: 'Você não possui nenhum item no carrinho, para adicioná-los vá para Início.',
  adicionarFrutas: 'Adicionar Frutas',
  erroUsuario: 'Erro! (cpf: 00000000000, senha: 12345)',
  nenhumItemCorr: 'Nenhum item corresponde a pesquisa!'
};
